name: Checks

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lin-checks:
    name: Linux Checks
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Rust
          uses: moonrepo/setup-rust@v0
          with:
            channel: stable
            profile: default

        - name: Check
          run: cargo check -p cobra-server

  win-checks:
    name: Windows Checks
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          profile: default
          targets: x86_64-pc-windows-msvc,i686-pc-windows-msvc

      - name: Check
        run: cargo check

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings
